=== asus200786/IssueTracker_HannaSushchanka/src/main/resources/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/users"
	xmlns:tns="http://www.example.org/users">
	<element name="users">
		<complexType>
			<sequence>
				<element name="users" type="tns:Users" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="Users">
		<sequence>
			<element name="user" type="tns:User" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="User">
		<sequence>
			<element name="login" type="string" />
			<element name="address" type="tns:Address" />
		</sequence>
	</complexType>
	<complexType name="Address">
		<attribute name="password" type="tns:password" />
		<attribute name="role" type="tns:RolesUser" />
		<attribute name="firstname" type="tns:userName" />
		<attribute name="lastname" type="tns:userName" />
		<attribute name="emailAddress" type="string" />
	</complexType>
	<simpleType name="userName">
		<restriction base="string">
			<!-- <pattern value="^[A-Z]+([a-zA-Z])*" /> -->
		</restriction>
	</simpleType>
	<simpleType name="password">
		<restriction base="string">
			<!-- <pattern value="^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\S+$).{5,}$" 
				/> -->
		</restriction>
	</simpleType>
	<simpleType name="RolesUser">
		<restriction base="string">
			<enumeration value="GUEST" />
			<enumeration value="USER" />
			<enumeration value="ADMINISTRATOR" />
		</restriction>
	</simpleType>
</schema>

=== asus200786/IssueTracker_HannaSushchanka/src/main/resources/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:tns="http://www.example.org/users" xsi:schemaLocation="http://www.example.org/users users.xsd">
	<!-- Login/Password: Asus200786@gmail.com/password; Dushiv@tut.by/dushik; 
		Jorjick@rambler.ru/jorick -->
	<users>
		<user>
			<login>Asus200786@gmail.com</login>
			<address password="5f4dcc3b5aa765d61d8327deb882cf99" role="ADMINISTRATOR"
				firstname="Hanna" lastname="Sushchanka" emailAddress="Asus200786@gmail.com" />
		</user>
		<user>
			<login>Dushiv@tut.by</login>
			<address password="c1e5965c5dcd3edce68293ebe486c642" role="USER"
				firstname="Ivan" lastname="Dushkevich" emailAddress="Dushiv@tut.by" />
		</user>
		<user>
			<login>Jorjick@rambler.ru</login>
			<address password="5f65b610ab9aae34f73d931d1fc249b2" role="USER"
				firstname="Georgij" lastname="Vajvichenskij" emailAddress="Jorjick@rambler.ru" />
		</user>
	</users>
</tns:users>
